name: achat_global_replica
description: "Exact replica of Achat Global voice chat app"
publish_to: 'none'
version: 1.0.0+3.16.01

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  audioplayers: ^5.2.1
  socket_io_client: ^2.0.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  flutter_sound: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/resource/
    - assets/resource/about/
    - assets/resource/avatar_h/
    - assets/resource/call_h/
    - assets/resource/chat_h/
    - assets/resource/country_h/
    - assets/resource/cp/
    - assets/resource/decoration_h/
    - assets/resource/evaluate_h/
    - assets/resource/finance/
    - assets/resource/gift/
    - assets/resource/guide_h/
    - assets/resource/home_h/
    - assets/resource/icon_h/
    - assets/resource/live_h/
    - assets/resource/live_h/award/
    - assets/fonts/
    - assets/packages/
    - assets/packages/car_game/res/
    - assets/packages/car_game/res/aac/
    - assets/voice_aac/
  
  fonts:
    - family: Dsdigib
      fonts:
        - asset: assets/fonts/Dsdigib.ttf
    - family: PkEffectFont
      fonts:
        - asset: assets/fonts/PkEffectFont.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf
    - family: OswaldSemiBold
      fonts:
        - asset: assets/fonts/OswaldSemiBold.ttf